version: '3.7'
services:
  postgres:
    container_name: game_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game
    ports:
      - '5432:5432'
    volumes:
      - game:/applis/docker-compose/db/game
volumes:
  game:
    external: true
